#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stdint.h>

#define UART_LINE_MAX_LEN          180U

#define MSG_TYPE_VITAL             1U
#define MSG_TYPE_LOADCELL          2U

#define WING_A                     0U
#define WING_B                     1U

#define ENABLE_UART_BYTE_ECHO      0
#define ENABLE_FAKE_UART_TEST      0
#define ENABLE_CAN_EXT_TEST        0
#define HEARTBEAT_ENABLE           1
#define CAN_TX_TIMEOUT_MS          100U

/*
 * RTOS switch:
 * 1 = use FreeRTOS Task/Queue/Mutex/Semaphore/Software timer flow.
 * 0 = keep original super-loop flow.
 * Note: when set to 1, the project must contain FreeRTOS middleware
 *       and include paths generated by STM32CubeMX/CubeIDE.
 */
#define APP_USE_FREERTOS          1

#define UART_LINE_QUEUE_LENGTH    8U
#define GATEWAY_TASK_STACK_WORDS  384U
#define CAN_ERROR_TASK_STACK_WORDS 256U
#define TEST_TASK_STACK_WORDS     256U
#define GATEWAY_TASK_PRIORITY     3U
#define CAN_ERROR_TASK_PRIORITY   2U
#define TEST_TASK_PRIORITY        1U
#define HEARTBEAT_PERIOD_MS       3000U
#define APP_RTOS_IRQ_PRIORITY     5U

#endif /* APP_CONFIG_H */
